apiVersion: batch/v1
kind: Job
metadata:
  name: nvidia-smi
  labels:
    name: nvidia-smi
spec:
  template:
    metadata:
      labels:
        name: nvidia-smi
    spec:
      containers:
      - name: nvidia-smi
        image: nvidia/cuda
        command: [ "nvidia-smi" ]
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        resources:
          requests:
            alpha.kubernetes.io/nvidia-gpu: 1 
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1 
        volumeMounts:
        - mountPath: /dev/nvidia0
          name: nvidia0
        - mountPath: /dev/nvidiactl
          name: nvidiactl
        - mountPath: /dev/nvidia-uvm
          name: nvidia-uvm
        - mountPath: /usr/local/nvidia/bin
          name: bin
        - mountPath: /usr/lib/nvidia
          name: lib
      volumes:
        - name: nvidia0
          hostPath: 
            path: /dev/nvidia0
        - name: nvidiactl
          hostPath: 
            path: /dev/nvidiactl
        - name: nvidia-uvm
          hostPath: 
            path: /dev/nvidia-uvm
        - name: bin
          hostPath: 
            path: /usr/lib/nvidia-367/bin
        - name: lib
          hostPath: 
            path: /usr/lib/nvidia-367
      restartPolicy: Never

